/**
 * 龙溪企服 - 房源库公开数据（自动生成，请勿手工修改）
 * 数据来源：xmOTP listings 表，仅同步“在租”房源。
 * 非公开字段不会写入官网。
 */

const propertiesList = [
  {
    "id": 31,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 58,
    "total_rent_month": 1999,
    "property_fee": 0,
    "floor_info": "815",
    "decoration": "1隔间+公区·湖+山景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 34.47,
    "notes": ""
  },
  {
    "id": 26,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 88,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "919",
    "decoration": "暗间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 30,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 90,
    "total_rent_month": 3150,
    "property_fee": 0,
    "floor_info": "806",
    "decoration": "2隔间+公区·山景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 32,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 118,
    "total_rent_month": 4484,
    "property_fee": 0,
    "floor_info": "816",
    "decoration": "2隔间+公区·湖景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 38.0,
    "notes": ""
  },
  {
    "id": 27,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 128,
    "total_rent_month": 4480,
    "property_fee": 0,
    "floor_info": "903",
    "decoration": "2隔间+公区·山景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 29,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 198,
    "total_rent_month": 4158,
    "property_fee": 0,
    "floor_info": "911",
    "decoration": "3隔间+公区·湖景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 21.0,
    "notes": ""
  },
  {
    "id": 28,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 208,
    "total_rent_month": 7696,
    "property_fee": 0,
    "floor_info": "910",
    "decoration": "4隔间+公区·湖景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 37.0,
    "notes": ""
  },
  {
    "id": 33,
    "district": "同安",
    "building_name": "合美大厦(美峰创谷5号楼)",
    "area_m2": 355,
    "total_rent_month": 13490,
    "property_fee": 0,
    "floor_info": "818",
    "decoration": "可定制格局·海景",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 38.0,
    "notes": ""
  },
  {
    "id": 108,
    "district": "同安",
    "building_name": "同业楼一期",
    "area_m2": 1894.51,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "三层302",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 109,
    "district": "同安",
    "building_name": "同业楼一期",
    "area_m2": 3571.17,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "四层南北楼",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 110,
    "district": "同安",
    "building_name": "同业楼一期",
    "area_m2": 3571.17,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "五层南北楼",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 106,
    "district": "同安",
    "building_name": "同业楼一期",
    "area_m2": 14740.88,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "六层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 107,
    "district": "同安",
    "building_name": "同业楼一期",
    "area_m2": 26081.29,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "七层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 114,
    "district": "同安",
    "building_name": "同翔通用厂房",
    "area_m2": 172.81,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "502B",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 111,
    "district": "同安",
    "building_name": "同翔通用厂房",
    "area_m2": 1054.5,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "二层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 112,
    "district": "同安",
    "building_name": "同翔通用厂房",
    "area_m2": 1364.501,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "三层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 113,
    "district": "同安",
    "building_name": "同翔通用厂房",
    "area_m2": 1364.501,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "四层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 7,
    "district": "同安",
    "building_name": "龙溪商务中心",
    "area_m2": 0,
    "total_rent_month": 1200,
    "property_fee": 0,
    "floor_info": "共享单间",
    "decoration": "共享办公",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 2,
    "district": "同安",
    "building_name": "龙溪商务中心",
    "area_m2": 68,
    "total_rent_month": 1380,
    "property_fee": 0,
    "floor_info": "103-2",
    "decoration": "大开间·独立门禁",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 20.29,
    "notes": ""
  },
  {
    "id": 3,
    "district": "同安",
    "building_name": "龙溪商务中心",
    "area_m2": 78,
    "total_rent_month": 1794,
    "property_fee": 0,
    "floor_info": "430",
    "decoration": "1+1格局",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 23.0,
    "notes": ""
  },
  {
    "id": 4,
    "district": "同安",
    "building_name": "龙溪商务中心",
    "area_m2": 130,
    "total_rent_month": 2990,
    "property_fee": 0,
    "floor_info": "109",
    "decoration": "2隔间+公区",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 23.0,
    "notes": ""
  },
  {
    "id": 6,
    "district": "同安",
    "building_name": "龙溪商务中心",
    "area_m2": 143,
    "total_rent_month": 3003,
    "property_fee": 0,
    "floor_info": "218",
    "decoration": "3间格局",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 21.0,
    "notes": ""
  },
  {
    "id": 5,
    "district": "同安",
    "building_name": "龙溪商务中心",
    "area_m2": 160,
    "total_rent_month": 3360,
    "property_fee": 0,
    "floor_info": "320",
    "decoration": "大开间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 21.0,
    "notes": ""
  },
  {
    "id": 243,
    "district": "思明",
    "building_name": "软件园二期",
    "area_m2": 55,
    "total_rent_month": 1800,
    "property_fee": 6,
    "floor_info": "望海路6-3四楼 V12",
    "decoration": "精装",
    "parking": "24小时空调",
    "lease_expiry": "",
    "unit_price_rent": 32.73,
    "notes": ""
  },
  {
    "id": 244,
    "district": "思明",
    "building_name": "软件园二期",
    "area_m2": 66,
    "total_rent_month": 2500,
    "property_fee": 6,
    "floor_info": "望海路6-3四楼 V16",
    "decoration": "精装",
    "parking": "24小时空调",
    "lease_expiry": "",
    "unit_price_rent": 37.88,
    "notes": ""
  },
  {
    "id": 242,
    "district": "思明",
    "building_name": "软件园二期",
    "area_m2": 96,
    "total_rent_month": 3300,
    "property_fee": 6,
    "floor_info": "望海路6-3四楼 V7",
    "decoration": "精装",
    "parking": "24小时空调",
    "lease_expiry": "",
    "unit_price_rent": 34.38,
    "notes": ""
  },
  {
    "id": 238,
    "district": "思明",
    "building_name": "软件园二期",
    "area_m2": 186,
    "total_rent_month": 6500,
    "property_fee": 6,
    "floor_info": "望海路6-2三楼 311",
    "decoration": "精装",
    "parking": "24小时空调",
    "lease_expiry": "",
    "unit_price_rent": 34.95,
    "notes": ""
  },
  {
    "id": 62,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 0,
    "total_rent_month": 3200,
    "property_fee": 0,
    "floor_info": "7楼(多种)",
    "decoration": "独立单间带采光窗·全新装修",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 63,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 88,
    "total_rent_month": 6000,
    "property_fee": 0,
    "floor_info": "406",
    "decoration": "1隔间·全套家具·朝南",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 68.18,
    "notes": ""
  },
  {
    "id": 72,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 108,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2105",
    "decoration": "全新装修·2隔间·朝西",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 67,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 135,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1205",
    "decoration": "全新装修·2隔间·双面采光",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 71,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 168,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2109",
    "decoration": "全新装修·2隔间·朝北",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 69,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 186,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1806",
    "decoration": "大工区·2隔间·朝南",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 70,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 200,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2002",
    "decoration": "全新装修·3隔间·朝北",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 64,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 220,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "701",
    "decoration": "3隔间·全套家具·双面采光",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 65,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 286,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1202",
    "decoration": "4隔间·电梯厅大门面·朝北",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 68,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 583,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1403",
    "decoration": "7隔间·三面采光·大工区",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 66,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 880,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1102/03",
    "decoration": "来客定制装修·可配家具",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 73,
    "district": "思明",
    "building_name": "通达国际中心",
    "area_m2": 1460,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "19F(整层)",
    "decoration": "12隔间·装修新·整层",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 37,
    "district": "湖里",
    "building_name": "合旺金谷T4",
    "area_m2": 72,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2617",
    "decoration": "1隔间+工区(6工位)·朝北",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 35,
    "district": "湖里",
    "building_name": "合旺金谷T4",
    "area_m2": 142,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2512",
    "decoration": "2隔间+工区(8工位)·朝北",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 36,
    "district": "湖里",
    "building_name": "合旺金谷T4",
    "area_m2": 148,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2407",
    "decoration": "2隔间+工区(8工位)·朝南",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 38,
    "district": "湖里",
    "building_name": "合旺金谷T4",
    "area_m2": 158,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2503",
    "decoration": "2隔间+工区(12工位)·朝西",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 39,
    "district": "湖里",
    "building_name": "合旺金谷T4",
    "area_m2": 195,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2603",
    "decoration": "4隔间+工区(8工位)·朝西",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 34,
    "district": "湖里",
    "building_name": "合旺金谷T4",
    "area_m2": 275,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "2402",
    "decoration": "4隔间+工区(18工位)·朝西",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 199,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "2301-L",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 192,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 73,
    "total_rent_month": 3700,
    "property_fee": 0,
    "floor_info": "2303-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 50.68,
    "notes": ""
  },
  {
    "id": 183,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 76,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "2305",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 52.63,
    "notes": ""
  },
  {
    "id": 184,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 76,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "2305-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 52.63,
    "notes": ""
  },
  {
    "id": 195,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 76,
    "total_rent_month": 3800,
    "property_fee": 0,
    "floor_info": "2302-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 50.0,
    "notes": ""
  },
  {
    "id": 196,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 76,
    "total_rent_month": 3800,
    "property_fee": 0,
    "floor_info": "2302",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 50.0,
    "notes": ""
  },
  {
    "id": 186,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 78,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "2305-3",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 51.28,
    "notes": ""
  },
  {
    "id": 187,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 78,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "2305-4",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 51.28,
    "notes": ""
  },
  {
    "id": 188,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 78,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "2305-5",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 51.28,
    "notes": ""
  },
  {
    "id": 189,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 78,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "2305-6",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 51.28,
    "notes": ""
  },
  {
    "id": 197,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 78,
    "total_rent_month": 3800,
    "property_fee": 0,
    "floor_info": "2302-4",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 48.72,
    "notes": ""
  },
  {
    "id": 185,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 128,
    "total_rent_month": 5760,
    "property_fee": 0,
    "floor_info": "2305-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 193,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 128,
    "total_rent_month": 5760,
    "property_fee": 0,
    "floor_info": "2303-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 194,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 135,
    "total_rent_month": 6075,
    "property_fee": 0,
    "floor_info": "2303-3",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 190,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 293,
    "total_rent_month": 13185,
    "property_fee": 0,
    "floor_info": "2306",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 182,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 300,
    "total_rent_month": 13500,
    "property_fee": 0,
    "floor_info": "2304",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 191,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 300,
    "total_rent_month": 13500,
    "property_fee": 0,
    "floor_info": "2303",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 198,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 300,
    "total_rent_month": 13500,
    "property_fee": 0,
    "floor_info": "2301",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 200,
    "district": "湖里",
    "building_name": "海西金融广场A栋",
    "area_m2": 398,
    "total_rent_month": 17910,
    "property_fee": 0,
    "floor_info": "1901",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 54,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 120,
    "total_rent_month": 4200,
    "property_fee": 0,
    "floor_info": "11栋302",
    "decoration": "精装·送40多夹层",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 53,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 125,
    "total_rent_month": 4125,
    "property_fee": 0,
    "floor_info": "11栋301",
    "decoration": "精装修",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.0,
    "notes": ""
  },
  {
    "id": 56,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 155,
    "total_rent_month": 4650,
    "property_fee": 0,
    "floor_info": "11栋308",
    "decoration": "层高5.8m",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.0,
    "notes": ""
  },
  {
    "id": 55,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 242,
    "total_rent_month": 7986,
    "property_fee": 0,
    "floor_info": "11栋306",
    "decoration": "层高5.8m·摄影电商风格",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.0,
    "notes": ""
  },
  {
    "id": 49,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 298,
    "total_rent_month": 11622,
    "property_fee": 0,
    "floor_info": "5A栋101",
    "decoration": "1楼非沿街·带装修送隔层",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 39.0,
    "notes": ""
  },
  {
    "id": 52,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 390,
    "total_rent_month": 13650,
    "property_fee": 0,
    "floor_info": "11栋203",
    "decoration": "层高5.9m·摄影企业拎包",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 57,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 397,
    "total_rent_month": 13101,
    "property_fee": 0,
    "floor_info": "11栋306+308",
    "decoration": "简装·上一家电商",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.0,
    "notes": ""
  },
  {
    "id": 48,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 950,
    "total_rent_month": 31350,
    "property_fee": 0,
    "floor_info": "5A栋301",
    "decoration": "层高5.8m·带装修",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.0,
    "notes": ""
  },
  {
    "id": 51,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 973,
    "total_rent_month": 28217,
    "property_fee": 0,
    "floor_info": "9栋2层",
    "decoration": "层高5.8m",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 29.0,
    "notes": ""
  },
  {
    "id": 58,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 2918,
    "total_rent_month": 110884,
    "property_fee": 0,
    "floor_info": "16栋(整栋)",
    "decoration": "1-3层·精装·沿主干道",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 38.0,
    "notes": ""
  },
  {
    "id": 50,
    "district": "湖里",
    "building_name": "翠林(厦门)中心",
    "area_m2": 3994,
    "total_rent_month": 147778,
    "property_fee": 0,
    "floor_info": "5栋(整栋)",
    "decoration": "1-4层·层高5.8m·园区C位",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 37.0,
    "notes": ""
  },
  {
    "id": 59,
    "district": "湖里",
    "building_name": "翠林(厦门)中心(商业)",
    "area_m2": 75,
    "total_rent_month": 4425,
    "property_fee": 0,
    "floor_info": "1栋",
    "decoration": "沿街店面·可上下水排烟",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 59.0,
    "notes": ""
  },
  {
    "id": 61,
    "district": "湖里",
    "building_name": "翠林(厦门)中心(商业)",
    "area_m2": 100,
    "total_rent_month": 5900,
    "property_fee": 0,
    "floor_info": "1栋",
    "decoration": "沿街店面·可上下水排烟",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 59.0,
    "notes": ""
  },
  {
    "id": 60,
    "district": "湖里",
    "building_name": "翠林(厦门)中心(商业)",
    "area_m2": 200,
    "total_rent_month": 11800,
    "property_fee": 0,
    "floor_info": "1栋",
    "decoration": "沿街店面·可上下水排烟",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 59.0,
    "notes": ""
  },
  {
    "id": 204,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 40,
    "total_rent_month": 1600,
    "property_fee": 0,
    "floor_info": "461",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 205,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 40,
    "total_rent_month": 1800,
    "property_fee": 0,
    "floor_info": "463",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 45.0,
    "notes": ""
  },
  {
    "id": 201,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 50,
    "total_rent_month": 1600,
    "property_fee": 0,
    "floor_info": "427",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 32.0,
    "notes": ""
  },
  {
    "id": 202,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 50,
    "total_rent_month": 2300,
    "property_fee": 0,
    "floor_info": "339",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 46.0,
    "notes": ""
  },
  {
    "id": 206,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 50,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "460",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 203,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 55,
    "total_rent_month": 2500,
    "property_fee": 0,
    "floor_info": "430",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 45.45,
    "notes": ""
  },
  {
    "id": 208,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 70,
    "total_rent_month": 3000,
    "property_fee": 0,
    "floor_info": "470",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 42.86,
    "notes": ""
  },
  {
    "id": 209,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 70,
    "total_rent_month": 2500,
    "property_fee": 0,
    "floor_info": "471",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 35.71,
    "notes": ""
  },
  {
    "id": 210,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 70,
    "total_rent_month": 3000,
    "property_fee": 0,
    "floor_info": "466",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 42.86,
    "notes": ""
  },
  {
    "id": 212,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 70,
    "total_rent_month": 3000,
    "property_fee": 0,
    "floor_info": "472",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 42.86,
    "notes": ""
  },
  {
    "id": 211,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 75,
    "total_rent_month": 2880,
    "property_fee": 0,
    "floor_info": "465",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 38.4,
    "notes": ""
  },
  {
    "id": 207,
    "district": "湖里",
    "building_name": "蔡塘·荣泰大厦",
    "area_m2": 80,
    "total_rent_month": 3300,
    "property_fee": 0,
    "floor_info": "438",
    "decoration": "精装",
    "parking": "停车费450元/月，季付400元/月",
    "lease_expiry": "",
    "unit_price_rent": 41.25,
    "notes": ""
  },
  {
    "id": 148,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 0,
    "total_rent_month": 1800,
    "property_fee": 0,
    "floor_info": "211",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 162,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 0,
    "total_rent_month": 3400,
    "property_fee": 0,
    "floor_info": "419之一",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 163,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 0,
    "total_rent_month": 3950,
    "property_fee": 0,
    "floor_info": "419",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 166,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 0,
    "total_rent_month": 3000,
    "property_fee": 0,
    "floor_info": "511",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 164,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 87,
    "total_rent_month": 3480,
    "property_fee": 5,
    "floor_info": "501",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 176,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 87,
    "total_rent_month": 3480,
    "property_fee": 5,
    "floor_info": "701",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 155,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 112,
    "total_rent_month": 4480,
    "property_fee": 5,
    "floor_info": "310",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 157,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 130,
    "total_rent_month": 5200,
    "property_fee": 5,
    "floor_info": "317",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 174,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 130,
    "total_rent_month": 5200,
    "property_fee": 5,
    "floor_info": "619",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 151,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 136,
    "total_rent_month": 5440,
    "property_fee": 5,
    "floor_info": "217",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 154,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 136,
    "total_rent_month": 5440,
    "property_fee": 5,
    "floor_info": "308",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 172,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 142,
    "total_rent_month": 5680,
    "property_fee": 5,
    "floor_info": "609",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 169,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 153,
    "total_rent_month": 6120,
    "property_fee": 5,
    "floor_info": "602",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 146,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 158,
    "total_rent_month": 6320,
    "property_fee": 5,
    "floor_info": "206",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 147,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 158,
    "total_rent_month": 6320,
    "property_fee": 5,
    "floor_info": "209",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 149,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 158,
    "total_rent_month": 6320,
    "property_fee": 5,
    "floor_info": "213",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 156,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 158,
    "total_rent_month": 6320,
    "property_fee": 5,
    "floor_info": "311",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 150,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 163,
    "total_rent_month": 6520,
    "property_fee": 5,
    "floor_info": "216",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 158,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 169,
    "total_rent_month": 6760,
    "property_fee": 5,
    "floor_info": "321",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 144,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 181,
    "total_rent_month": 7240,
    "property_fee": 5,
    "floor_info": "203",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 145,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 181,
    "total_rent_month": 7240,
    "property_fee": 5,
    "floor_info": "205",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 159,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 206,
    "total_rent_month": 8240,
    "property_fee": 5,
    "floor_info": "415",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 153,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 238,
    "total_rent_month": 9520,
    "property_fee": 5,
    "floor_info": "307",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 161,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 261,
    "total_rent_month": 10440,
    "property_fee": 5,
    "floor_info": "418",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 168,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 261,
    "total_rent_month": 10440,
    "property_fee": 5,
    "floor_info": "518",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 180,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 261,
    "total_rent_month": 10440,
    "property_fee": 5,
    "floor_info": "918",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 152,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 271,
    "total_rent_month": 10840,
    "property_fee": 5,
    "floor_info": "302",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 167,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 283,
    "total_rent_month": 11320,
    "property_fee": 5,
    "floor_info": "512",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 171,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 283,
    "total_rent_month": 11320,
    "property_fee": 5,
    "floor_info": "608",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 143,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 317,
    "total_rent_month": 12680,
    "property_fee": 5,
    "floor_info": "202",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 160,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 324,
    "total_rent_month": 12960,
    "property_fee": 5,
    "floor_info": "416",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 175,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 337,
    "total_rent_month": 13480,
    "property_fee": 5,
    "floor_info": "622",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 173,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 346,
    "total_rent_month": 13840,
    "property_fee": 5,
    "floor_info": "610",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 178,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 434,
    "total_rent_month": 17360,
    "property_fee": 5,
    "floor_info": "716",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 170,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 551,
    "total_rent_month": 22040,
    "property_fee": 5,
    "floor_info": "605",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 177,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 551,
    "total_rent_month": 22040,
    "property_fee": 5,
    "floor_info": "705",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 165,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 758,
    "total_rent_month": 30320,
    "property_fee": 5,
    "floor_info": "509",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 179,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 758,
    "total_rent_month": 30320,
    "property_fee": 5,
    "floor_info": "916",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 181,
    "district": "湖里",
    "building_name": "锦厦科技A栋",
    "area_m2": 2700,
    "total_rent_month": 108000,
    "property_fee": 5,
    "floor_info": "8楼整层",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 118,
    "district": "翔安",
    "building_name": "五洲科技城",
    "area_m2": 1367.58,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "301",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 117,
    "district": "翔安",
    "building_name": "五洲科技城",
    "area_m2": 1526.97,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "202",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 119,
    "district": "翔安",
    "building_name": "五洲科技城",
    "area_m2": 1526.97,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "501",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 115,
    "district": "翔安",
    "building_name": "五洲科技城",
    "area_m2": 1736.56,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "401",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 116,
    "district": "翔安",
    "building_name": "五洲科技城",
    "area_m2": 1736.56,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "502",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 129,
    "district": "翔安",
    "building_name": "八方通用厂房",
    "area_m2": 737.06,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "4层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 127,
    "district": "翔安",
    "building_name": "八方通用厂房",
    "area_m2": 1876.743,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "9#厂房301",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 128,
    "district": "翔安",
    "building_name": "八方通用厂房",
    "area_m2": 1876.743,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "12#生产服务设施用房3层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 141,
    "district": "翔安",
    "building_name": "智能制造三期",
    "area_m2": 173.87,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "205",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 142,
    "district": "翔安",
    "building_name": "智能制造三期",
    "area_m2": 613.63,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "303",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 140,
    "district": "翔安",
    "building_name": "智能制造三期",
    "area_m2": 629.79,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "203",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 137,
    "district": "翔安",
    "building_name": "智能制造三期",
    "area_m2": 1715.16,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "302",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 138,
    "district": "翔安",
    "building_name": "智能制造三期",
    "area_m2": 1844.73,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "501",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 139,
    "district": "翔安",
    "building_name": "智能制造三期",
    "area_m2": 2054.2,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "201",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 126,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 0,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "302",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 122,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 731.97,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "102",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 123,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 920.72,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "101",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 121,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 951.23,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "502",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 120,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 1259.7,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "202",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 124,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 1741.77,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "201",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 125,
    "district": "翔安",
    "building_name": "特盈园区",
    "area_m2": 1741.77,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "301",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 130,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 353.09,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "一层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 131,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 1041.26,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "二层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 134,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 1105.15,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "五层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 135,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 1105.15,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "六层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 136,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 1105.15,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "十二层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 132,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 1641.31,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "三层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 133,
    "district": "翔安",
    "building_name": "科技产品展示中心",
    "area_m2": 1641.31,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "四层",
    "decoration": "毛坯",
    "parking": "有",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 21,
    "district": "翔安",
    "building_name": "顶翔建业大厦A栋10楼",
    "area_m2": 85,
    "total_rent_month": 2600,
    "property_fee": 0,
    "floor_info": "1007-3",
    "decoration": "1+1·朝南",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.59,
    "notes": ""
  },
  {
    "id": 20,
    "district": "翔安",
    "building_name": "顶翔建业大厦A栋10楼",
    "area_m2": 125,
    "total_rent_month": 3800,
    "property_fee": 0,
    "floor_info": "1008-2",
    "decoration": "2+1",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.4,
    "notes": ""
  },
  {
    "id": 19,
    "district": "翔安",
    "building_name": "顶翔建业大厦A栋10楼",
    "area_m2": 185,
    "total_rent_month": 6500,
    "property_fee": 0,
    "floor_info": "1008-1",
    "decoration": "3+1边套·带前台",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.14,
    "notes": ""
  },
  {
    "id": 236,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 40,
    "total_rent_month": 1000,
    "property_fee": 0,
    "floor_info": "616-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 25.0,
    "notes": ""
  },
  {
    "id": 223,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 50,
    "total_rent_month": 1300,
    "property_fee": 0,
    "floor_info": "608-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 26.0,
    "notes": ""
  },
  {
    "id": 224,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 50,
    "total_rent_month": 1300,
    "property_fee": 0,
    "floor_info": "608-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 26.0,
    "notes": ""
  },
  {
    "id": 237,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 50,
    "total_rent_month": 1300,
    "property_fee": 0,
    "floor_info": "616-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 26.0,
    "notes": ""
  },
  {
    "id": 215,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "603-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 216,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "603-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 217,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "603-3",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 218,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "603-5",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 219,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "605-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 220,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2000,
    "property_fee": 0,
    "floor_info": "605-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 33.33,
    "notes": ""
  },
  {
    "id": 227,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2100,
    "property_fee": 0,
    "floor_info": "610-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 228,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2100,
    "property_fee": 0,
    "floor_info": "610-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 229,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2100,
    "property_fee": 0,
    "floor_info": "611-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 230,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2100,
    "property_fee": 0,
    "floor_info": "611-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 233,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2100,
    "property_fee": 0,
    "floor_info": "613-2",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 234,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 60,
    "total_rent_month": 2100,
    "property_fee": 0,
    "floor_info": "613-3",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 214,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 120,
    "total_rent_month": 3700,
    "property_fee": 0,
    "floor_info": "602",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.83,
    "notes": ""
  },
  {
    "id": 221,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 120,
    "total_rent_month": 3700,
    "property_fee": 0,
    "floor_info": "606",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.83,
    "notes": ""
  },
  {
    "id": 231,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 120,
    "total_rent_month": 3800,
    "property_fee": 0,
    "floor_info": "612",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 31.67,
    "notes": ""
  },
  {
    "id": 232,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 120,
    "total_rent_month": 3800,
    "property_fee": 0,
    "floor_info": "613-1",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 31.67,
    "notes": ""
  },
  {
    "id": 222,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 130,
    "total_rent_month": 4000,
    "property_fee": 0,
    "floor_info": "607",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.77,
    "notes": ""
  },
  {
    "id": 226,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 130,
    "total_rent_month": 4200,
    "property_fee": 0,
    "floor_info": "609",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 32.31,
    "notes": ""
  },
  {
    "id": 235,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 130,
    "total_rent_month": 4200,
    "property_fee": 0,
    "floor_info": "615",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 32.31,
    "notes": ""
  },
  {
    "id": 225,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 150,
    "total_rent_month": 4500,
    "property_fee": 0,
    "floor_info": "608-3",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 30.0,
    "notes": ""
  },
  {
    "id": 213,
    "district": "翔安",
    "building_name": "顶翔建业大厦B座6楼",
    "area_m2": 270,
    "total_rent_month": 8500,
    "property_fee": 0,
    "floor_info": "601",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 31.48,
    "notes": ""
  },
  {
    "id": 83,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 90,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1208",
    "decoration": "1隔间+1公区·精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 79,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 95,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "807",
    "decoration": "1隔间+1公区·精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 78,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 106,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "805",
    "decoration": "2隔间+1公区·精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 81,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 112,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "902-2",
    "decoration": "3隔间·精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 84,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 130,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "505",
    "decoration": "3隔间+1公区·精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 82,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 180,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "907",
    "decoration": "大开间·精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 86,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 811,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "12楼半层",
    "decoration": "精装",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 85,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 820,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "11层半层",
    "decoration": "毛坯/可定制装修",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 87,
    "district": "集美",
    "building_name": "奥佳华集美创新大楼",
    "area_m2": 1350,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "7层整层",
    "decoration": "精装/可定制装修",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 94,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 135,
    "total_rent_month": 4725,
    "property_fee": 0,
    "floor_info": "313",
    "decoration": "2隔间·10工位·电梯口2隔间户型",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 95,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 165,
    "total_rent_month": 5775,
    "property_fee": 0,
    "floor_info": "306",
    "decoration": "3隔间·8工位·3个大隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 96,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 208,
    "total_rent_month": 7280,
    "property_fee": 0,
    "floor_info": "308",
    "decoration": "3隔间·10工位·边套全套家具",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 97,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 252,
    "total_rent_month": 8820,
    "property_fee": 0,
    "floor_info": "508",
    "decoration": "3隔间·8工位·3个超大直播间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 99,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 278,
    "total_rent_month": 9730,
    "property_fee": 0,
    "floor_info": "305",
    "decoration": "3-5隔间·20工位·朝南电梯口",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 98,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 296,
    "total_rent_month": 10360,
    "property_fee": 0,
    "floor_info": "602",
    "decoration": "4隔间·18工位·朝南电梯口",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 100,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 373,
    "total_rent_month": 13055,
    "property_fee": 0,
    "floor_info": "301",
    "decoration": "6隔间·30工位·西南边套",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 101,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 415,
    "total_rent_month": 14525,
    "property_fee": 0,
    "floor_info": "705",
    "decoration": "13隔间·12工位·隔间多",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 103,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 568,
    "total_rent_month": 19880,
    "property_fee": 0,
    "floor_info": "1103",
    "decoration": "6隔间·50工位·电梯口定制",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 102,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 619,
    "total_rent_month": 21665,
    "property_fee": 0,
    "floor_info": "302",
    "decoration": "5隔间·50-70工位·定制户型装修边套",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 104,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 992,
    "total_rent_month": 34720,
    "property_fee": 0,
    "floor_info": "301+302",
    "decoration": "5隔间·70-100工位·电梯口定制双边边套",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 105,
    "district": "集美",
    "building_name": "富春产业园1号楼",
    "area_m2": 2088,
    "total_rent_month": 73080,
    "property_fee": 0,
    "floor_info": "13毛坯整层",
    "decoration": "10隔间·200工位·定制装修/层高5.4米",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 74,
    "district": "集美",
    "building_name": "软件园三期A02栋",
    "area_m2": 178,
    "total_rent_month": 7654,
    "property_fee": 0,
    "floor_info": "1101-5",
    "decoration": "2隔间+工区·带储物间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 43.0,
    "notes": ""
  },
  {
    "id": 75,
    "district": "集美",
    "building_name": "软件园三期A02栋",
    "area_m2": 198,
    "total_rent_month": 8514,
    "property_fee": 0,
    "floor_info": "1203-2",
    "decoration": "3隔间+工区·带储物间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 43.0,
    "notes": ""
  },
  {
    "id": 11,
    "district": "集美",
    "building_name": "软件园三期A04栋",
    "area_m2": 139,
    "total_rent_month": 4726,
    "property_fee": 0,
    "floor_info": "703-1",
    "decoration": "2+1带家具",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 34.0,
    "notes": ""
  },
  {
    "id": 16,
    "district": "集美",
    "building_name": "软件园三期B01栋",
    "area_m2": 0,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "411",
    "decoration": "1大厅",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 15,
    "district": "集美",
    "building_name": "软件园三期B01栋",
    "area_m2": 381,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "405",
    "decoration": "1大厅+6隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 77,
    "district": "集美",
    "building_name": "软件园三期B02栋",
    "area_m2": 89,
    "total_rent_month": 3827,
    "property_fee": 0,
    "floor_info": "1601-6",
    "decoration": "1隔间+工区",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 43.0,
    "notes": ""
  },
  {
    "id": 76,
    "district": "集美",
    "building_name": "软件园三期B02栋",
    "area_m2": 338,
    "total_rent_month": 14534,
    "property_fee": 0,
    "floor_info": "1601-8",
    "decoration": "4隔间+工区·边套",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 43.0,
    "notes": ""
  },
  {
    "id": 88,
    "district": "集美",
    "building_name": "软件园三期B02栋",
    "area_m2": 360,
    "total_rent_month": 14400,
    "property_fee": 0,
    "floor_info": "901-2",
    "decoration": "4隔间·30工位·新装修",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 14,
    "district": "集美",
    "building_name": "软件园三期C05栋",
    "area_m2": 155.2,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1103-2",
    "decoration": "1大厅+2隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 89,
    "district": "集美",
    "building_name": "软件园三期D17栋",
    "area_m2": 125,
    "total_rent_month": 4375,
    "property_fee": 0,
    "floor_info": "602",
    "decoration": "2隔间·8工位·正南全屋家具",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 90,
    "district": "集美",
    "building_name": "软件园三期D17栋",
    "area_m2": 252,
    "total_rent_month": 8820,
    "property_fee": 0,
    "floor_info": "706",
    "decoration": "5隔间·16工位·新装修/电梯口",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 91,
    "district": "集美",
    "building_name": "软件园三期D17栋",
    "area_m2": 288,
    "total_rent_month": 10080,
    "property_fee": 0,
    "floor_info": "707",
    "decoration": "3隔间·20工位·边套全屋采光",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 92,
    "district": "集美",
    "building_name": "软件园三期D17栋",
    "area_m2": 588,
    "total_rent_month": 20580,
    "property_fee": 0,
    "floor_info": "502",
    "decoration": "6隔间·60工位·电梯口边套定制",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 93,
    "district": "集美",
    "building_name": "软件园三期D17栋",
    "area_m2": 737,
    "total_rent_month": 25795,
    "property_fee": 0,
    "floor_info": "805",
    "decoration": "6隔间·70工位·电梯口东南北边套全明户型",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 35.0,
    "notes": ""
  },
  {
    "id": 17,
    "district": "集美",
    "building_name": "软件园三期F05栋",
    "area_m2": 89,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "501-6",
    "decoration": "1大厅+1隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 8,
    "district": "集美",
    "building_name": "软件园三期F26栋",
    "area_m2": 0,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "1202-3",
    "decoration": "1+1带家具",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 10,
    "district": "集美",
    "building_name": "软件园三期F26栋",
    "area_m2": 105,
    "total_rent_month": 2415,
    "property_fee": 0,
    "floor_info": "1204-2",
    "decoration": "1+1月底可搬",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 23.0,
    "notes": ""
  },
  {
    "id": 18,
    "district": "集美",
    "building_name": "软件园三期F26栋",
    "area_m2": 330,
    "total_rent_month": 0,
    "property_fee": 0,
    "floor_info": "503-1",
    "decoration": "1大厅+6隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 0,
    "notes": ""
  },
  {
    "id": 9,
    "district": "集美",
    "building_name": "软件园三期F26栋",
    "area_m2": 468,
    "total_rent_month": 10764,
    "property_fee": 0,
    "floor_info": "1203-3",
    "decoration": "1+1带露台",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 23.0,
    "notes": ""
  },
  {
    "id": 13,
    "district": "集美",
    "building_name": "迦阁软件园三期B14栋",
    "area_m2": 108,
    "total_rent_month": 4320,
    "property_fee": 0,
    "floor_info": "401-2",
    "decoration": "2个隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 40.0,
    "notes": ""
  },
  {
    "id": 12,
    "district": "集美",
    "building_name": "迦阁软件园三期F02栋",
    "area_m2": 109,
    "total_rent_month": 2398,
    "property_fee": 0,
    "floor_info": "101-5",
    "decoration": "2个隔间",
    "parking": "",
    "lease_expiry": "",
    "unit_price_rent": 22.0,
    "notes": ""
  }
];

window.propertiesList = propertiesList;
